name: njsscan Security Scan

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:
  njsscan:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Install njsscan
        run: pip install njsscan


      - name: Run njsscan
        run: njsscan --directory .
